/**
 * Phase 3 — File Digest
 *
 * Walks the per-file results emitted by the filtering stages, computes some
 * lightweight statistics, and writes a `_file_digest.md` summary that Claude
 * reads before opening any file.
 *
 * This is the document that lets Claude answer "what's in these files?"
 * without scanning them. If the digest looks suspicious (e.g. the error spike
 * is outside the customer-reported window) Claude can still open the original.
 */

'use strict';

const fs = require('fs');
const readline = require('readline');
const path = require('path');
const zlib = require('zlib');

// --- Stat helpers ----------------------------------------------------------

function bytesHuman(n) {
  if (n < 1024) return n + ' B';
  if (n < 1024 ** 2) return (n / 1024).toFixed(1) + ' KB';
  if (n < 1024 ** 3) return (n / 1024 ** 2).toFixed(1) + ' MB';
  return (n / 1024 ** 3).toFixed(2) + ' GB';
}

function reductionPct(originalBytes, filteredBytes) {
  if (!originalBytes || filteredBytes >= originalBytes) return 0;
  return Math.round(((originalBytes - filteredBytes) / originalBytes) * 100);
}

/**
 * Cheap log-stat scan: counts errors/warnings and pulls the top N error
 * messages by frequency. Operates on the filtered file when available so the
 * scan is bounded.
 */
async function scanLogStats(filePath, opts = {}) {
  const top = opts.top || 5;
  const maxLines = opts.maxLines || 200000;
  const counts = new Map();
  let errorLines = 0;
  let warnLines = 0;
  let totalLines = 0;

  const isGz = filePath.endsWith('.gz');
  const stream = isGz
    ? fs.createReadStream(filePath).pipe(zlib.createGunzip())
    : fs.createReadStream(filePath);

  const rl = readline.createInterface({ input: stream, crlfDelay: Infinity });

  for await (const line of rl) {
    totalLines++;
    if (totalLines > maxLines) break;
    const l = line;
    let isErr = false;
    let isWarn = false;
    if (/TBLV0\b|\bERROR\b|\bFATAL\b|\bCRITICAL\b|\bPANIC\b/i.test(l)) { errorLines++; isErr = true; }
    else if (/TBLV1\b|\bWARN(?:ING)?\b/i.test(l)) { warnLines++; isWarn = true; }

    if (isErr || isWarn) {
      // Strip leading timestamp + level token and keep the next ~80 chars as a key.
      const key = l
        .replace(/^\[?\d[\d\-T:./\s]+\]?/, '')              // timestamp
        .replace(/^\s*(?:TBLV[01]|ERROR|WARN(?:ING)?|FATAL|CRITICAL|PANIC)\s*[:>-]?\s*/i, '')
        .trim()
        .slice(0, 100);
      counts.set(key, (counts.get(key) || 0) + 1);
    }
  }

  const ranked = Array.from(counts.entries())
    .sort((a, b) => b[1] - a[1])
    .slice(0, top)
    .map(([msg, n]) => ({ msg, count: n }));

  return { totalLines, errorLines, warnLines, topMessages: ranked };
}

// --- Digest assembly -------------------------------------------------------

/**
 * @param {object} input
 * @param {string} input.ticketNumber
 * @param {object} input.extractedContext  (the ExtractedContext object from Stage 1)
 * @param {Array<object>} input.fileReports   one per file, see shape below
 *
 * fileReport shape (one of):
 *   { kind: 'log',  filePath, originalBytes, filteredBytes?, mode, skipped, skippedReason?, outputPath?, stats? }
 *   { kind: 'cdr',  filePath, originalBytes, filteredBytes?, originalRows, filteredRows, successCount, failureCount, outputPath?, skipped, skippedReason? }
 *   { kind: 'pcap', filePath, originalBytes, filteredBytes?, displayFilter?, outputPath?, skipped, skippedReason? }
 *   { kind: 'other', filePath, originalBytes }
 */
function renderDigestMarkdown(input) {
  const { ticketNumber, extractedContext: ctx, fileReports = [] } = input;
  const lines = [];
  lines.push(`# File Digest — Ticket ${ticketNumber}`);
  lines.push('');
  lines.push('_Auto-generated by the preprocessor pipeline. Read this before opening individual files._');
  lines.push('');

  // Extracted context summary
  if (ctx) {
    lines.push('## Extracted Context (from customer description)');
    if (ctx.timeRanges?.length) {
      lines.push('- **Time references:**');
      for (const tr of ctx.timeRanges) {
        const label = tr.kind === 'range' ? `${tr.start} → ${tr.end}` : `at ${tr.start}`;
        lines.push(`  - ${label} _(confidence: ${tr.confidence})_`);
      }
    }
    if (ctx.ipAddresses?.length) lines.push(`- **IP addresses:** ${ctx.ipAddresses.join(', ')}`);
    if (ctx.phoneNumbers?.length) lines.push(`- **Phone numbers:** ${ctx.phoneNumbers.join(', ')}`);
    if (ctx.errorCodes?.length) {
      const codes = ctx.errorCodes.map((c) => `${c.code} ${c.description}`).join(', ');
      lines.push(`- **Error codes mentioned:** ${codes}`);
    }
    if (ctx.errorKeywords?.length) lines.push(`- **Error keywords:** ${ctx.errorKeywords.join(', ')}`);
    if (ctx.sipCallIds?.length) lines.push(`- **SIP Call-IDs:** ${ctx.sipCallIds.join(', ')}`);
    if (ctx.affectedServices?.length) lines.push(`- **Affected services:** ${ctx.affectedServices.join(', ')}`);
    if (ctx.frequency && ctx.frequency !== 'unknown') lines.push(`- **Frequency:** ${ctx.frequency}`);
    lines.push('');
  }

  // Per-file summaries
  lines.push('## Files');
  if (fileReports.length === 0) {
    lines.push('_No files attached._');
    lines.push('');
    return lines.join('\n');
  }

  for (const r of fileReports) {
    const name = path.basename(r.filePath);
    lines.push('');
    lines.push(`### ${name}`);
    lines.push(`- **Original size:** ${bytesHuman(r.originalBytes)}`);

    if (r.kind === 'archive') {
      // Archive entry: render extraction info + nested children. Even if the
      // archive itself has skipped=true (e.g. extraction error), we still want
      // to show what we tried.
      if (r.skipped) {
        lines.push(`- **Pre-extracted:** no — ${r.skippedReason}`);
        lines.push(`- **Read this path:** \`${r.filePath}\` _(Claude must extract it itself)_`);
        continue;
      }
      lines.push(`- **Pre-extracted to:** \`${r.extractedAt}\``);
      lines.push(`- **Extracted contents:** ${r.totalExtractedFiles} files, ${bytesHuman(r.totalExtractedBytes)}`);
      const filteredKids = (r.childReports || []).filter((c) => !c.skipped && c.outputPath);
      if (filteredKids.length > 0) {
        lines.push(`- **Filtered:** ${filteredKids.length} of ${r.childReports.length} files (${bytesHuman(r.filteredBytes)} retained)`);
      } else {
        lines.push(`- **Filtered:** no children matched filters; read originals from the extraction dir`);
      }
      lines.push('');
      lines.push('  **Files inside this archive:**');
      for (const c of (r.childReports || [])) {
        const childName = path.basename(c.filePath);
        if (c.skipped) {
          lines.push(`  - \`${childName}\` _(${bytesHuman(c.originalBytes)}, ${c.skippedReason})_ → \`${c.filePath}\``);
        } else if (c.outputPath) {
          const reduction = reductionPct(c.originalBytes, c.filteredBytes);
          lines.push(`  - \`${childName}\` _(${bytesHuman(c.originalBytes)} → ${bytesHuman(c.filteredBytes)}, -${reduction}%)_ → \`${c.outputPath}\``);
        } else {
          lines.push(`  - \`${childName}\` _(${bytesHuman(c.originalBytes)})_ → \`${c.filePath}\``);
        }
      }
      continue;
    }

    if (r.skipped) {
      lines.push(`- **Filtered:** no — ${r.skippedReason}`);
      lines.push(`- **Read this path:** \`${r.filePath}\``);
      continue;
    }

    if (r.outputPath) {
      lines.push(`- **Filtered size:** ${bytesHuman(r.filteredBytes)} _(${reductionPct(r.originalBytes, r.filteredBytes)}% reduction)_`);
      lines.push(`- **Read this path:** \`${r.outputPath}\` _(filtered)_`);
      lines.push(`- **Original (fallback):** \`${r.filePath}\``);
    } else {
      lines.push(`- **Read this path:** \`${r.filePath}\``);
    }

    if (r.kind === 'log') {
      if (r.mode) lines.push(`- **Filter mode:** ${r.mode}`);
      if (r.stats) {
        lines.push(`- **Errors in window:** ${r.stats.errorLines}`);
        lines.push(`- **Warnings in window:** ${r.stats.warnLines}`);
        if (r.stats.topMessages?.length) {
          lines.push('- **Top messages:**');
          for (const t of r.stats.topMessages) {
            const safe = t.msg.replace(/[\r\n]/g, ' ');
            lines.push(`  - ${t.count}× "${safe}"`);
          }
        }
      }
    }

    if (r.kind === 'cdr') {
      lines.push(`- **Rows:** ${r.originalRows} original → ${r.filteredRows} matched`);
      if (r.successCount + r.failureCount > 0) {
        const total = r.successCount + r.failureCount;
        const rate = ((r.successCount / total) * 100).toFixed(1);
        lines.push(`- **Success rate (matched rows):** ${rate}% (${r.successCount} ok / ${r.failureCount} fail)`);
      }
    }

    if (r.kind === 'pcap') {
      if (r.displayFilter) lines.push(`- **tshark filter:** \`${r.displayFilter}\``);
    }
  }

  lines.push('');
  return lines.join('\n');
}

module.exports = {
  renderDigestMarkdown,
  scanLogStats,
  bytesHuman,
  reductionPct,
};
